### ISSUE TITLE
Suggestion: for vinyl textures xshp format for this tool update

### ISSUE THREAD

**Issue by UB833** [d3g0n-byte/RAGE-Console-Resource-Converter#2]
I just wanted to extract both vector vinyls and opponent preset vinyls so it doesn't extract with this tool just because this format is not supported yet.

please I request for making the vinyls format to be extractable with this tool.

EDIT: same for .xov file

**Comment by ImpossibleEchoes** [comment]
no more updates(

**Comment by UB833** [comment]
aw man. :(
